[package]
name = "wl_expr"
version = "0.1.0"
authors = ["Connor Gray <accounts@connorgray.com>"]

[dependencies]
string-interner = "^0.6"
lazy_static = "^0.2"
static_assertions = "^0.2"
ordered-float = "^0.5"