[package]
name = "wl-expr"
version = "0.1.0"
authors = ["Connor Gray <accounts@connorgray.com>"]
publish = false

[dependencies]
string-interner = "^0.6"
lazy_static = "^1.0"
static_assertions = "^1.1.0"
ordered-float = "1"