[package]
name = "wl-expr-core"
version = "0.1.0"
authors = ["Connor Gray <connorg@wolfram.com>"]
edition = "2018"
publish = false

[dependencies]
string-interner = "^0.7.1"
lazy_static = "^1.0"
static_assertions = "^1.1.0"
ordered-float = "1"
